version: "3"

services:

  postgres:
    container_name: aouis-db
    image: postgres:15-bullseye
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  api:
    container_name: aouis-api
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./AouisApi:/app/AouisApi
      - ./Products:/app/Products
      - ./Accounts:/app/Accounts
      - ./Categories:/app/Categories
      - ./Transactions:/app/Transactions
      - ./htmlcov:/app/htmlcov
    ports:
      - 8000:8000
    depends_on:
      - postgres