version: "3"

services:
  web:
    container_name: aouis-api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./AouisApi:/app/AouisApi
      - ./Accounts:/app/Accounts
      - ./Products:/app/Products
      - ./Categories:/app/Categories
    ports:
      - 8000:8000

  db:
    container_name: aouis-db
    image: postgres
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
