# Generated by Django 4.2.1 on 2023-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoris',
            field=models.ManyToManyField(blank=True, to='Products.product'),
        ),
    ]
